return {
	n = {
		["bl"] = { "<cmd> bnext <cr>", desc="Goto next buffer" },
		["bh"] = { "<cmd> bprevious <cr>", desc="Goto prev tab" },
		["bf"] = { "<cmd> bfirst <cr>", desc="Goto first tab" },
		["be"] = { "<cmd> blast <cr>", desc="Goto last tab" },
		["bd"] = { "<cmd> bd <cr>", desc="close current file" },
		["tl"] = { "<cmd> tabnext <cr>", desc="Goto next tab" },
		["th"] = { "<cmd> tabprevious <cr>", desc="Goto prev tab" },
		["tf"] = { "<cmd> tabfirst <cr>", desc="Goto first tab" },
		["te"] = { "<cmd> tablast <cr>", desc="Goto last tab" },
		["td"] = { "<cmd> tabclose <cr>", desc="close current tab" },
		["gk"] = { "<cmd> Man <cr>", desc="Goto manual" },
		[";h"] = { "<C-w>h", desc="Window left" },
		[";l"] = { "<C-w>l", desc="Window right" },
		[";j"] = { "<C-w>j", desc="Window down" },
		[";k"] = { "<C-w>k", desc="Window up" },
		[";q"] = { "<cmd> cclose <cr>", desc="close quickfix list" },
		["<leader>d"] = { function() vim.fn.chdir(vim.fn.expand("%:p:h")) end, desc="change current directory" },
		["<leader>a"] = { function() vim.cmd(string.format("Neotree toggle %s", vim.fn.expand("%:p:h"))) end, desc="Toggle current file neotree" },
	},
}
